"""
Principal Designer AI Service

This is the BRAIN of the MASTER level system.
Takes product info and generates 4 UNIQUE, PROFESSIONAL design frameworks
dynamically tailored to the specific product.

Each framework includes:
- Exact color palette with hex codes and distribution ratios
- Specific typography (font names, weights, sizes)
- Headlines and copy for each of 5 images
- Story arc tailored to the product
- Layout specifications
- Shadow and lighting specs
- Amazon-specific optimizations

This is NOT static presets - this is AI thinking like a Principal Designer
at Apple, Nike, or a top agency.
"""

import json
import logging
from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field, asdict
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


# ============================================================================
# DATA STRUCTURES FOR DESIGN FRAMEWORKS
# ============================================================================

@dataclass
class ColorSpec:
    """Exact color specification with role"""
    hex: str                    # e.g., "#BDAEC9"
    name: str                   # e.g., "Soft Lilac"
    role: str                   # "primary", "secondary", "accent", "text", "background"
    usage: str                  # e.g., "60% - backgrounds, main elements"


@dataclass
class TypographySpec:
    """Exact typography specification"""
    headline_font: str          # e.g., "Montserrat"
    headline_weight: str        # e.g., "Bold" or "700"
    headline_size: str          # e.g., "48px"
    subhead_font: str           # e.g., "Montserrat"
    subhead_weight: str         # e.g., "Regular" or "400"
    subhead_size: str           # e.g., "24px"
    body_font: str              # e.g., "Inter"
    body_weight: str            # e.g., "Regular"
    body_size: str              # e.g., "16px"
    letter_spacing: str         # e.g., "0.5px"


@dataclass
class ImageCopy:
    """Copy for a single image"""
    image_number: int           # 1-6
    image_type: str             # main, infographic_1, infographic_2, lifestyle, transformation, comparison
    headline: str               # Main headline (can be empty for main image)
    subhead: Optional[str]      # Optional subheadline
    feature_callouts: List[str] # Feature bullet points (for infographics)
    cta: Optional[str]          # Call to action


@dataclass
class StoryArc:
    """The narrative arc across all 6 images (Hero's Journey)"""
    theme: str                  # Overall story theme
    hook: str                   # Image 1 - INTRIGUE: What grabs attention
    reveal: str                 # Image 2 - TRUST: What we're revealing
    proof: str                  # Image 3 - BELONGING: How we prove it
    dream: str                  # Image 4 - DESIRE: The aspiration
    transform: str = ""         # Image 5 - TRANSFORMATION: The hero's journey (optional for backward compat)
    close: str = ""             # Image 6 - URGENCY: The final FOMO push


@dataclass
class LayoutSpec:
    """Layout specifications"""
    composition_style: str      # e.g., "centered symmetric", "dynamic asymmetric"
    whitespace_philosophy: str  # e.g., "generous breathing room", "dense and impactful"
    product_prominence: str     # e.g., "hero focus", "contextual integration"
    text_placement: str         # e.g., "left-aligned blocks", "centered hierarchy"
    visual_flow: str            # e.g., "Z-pattern", "radial from product"


@dataclass
class VisualTreatment:
    """Visual treatment specifications"""
    lighting_style: str         # e.g., "soft diffused from top-left"
    shadow_spec: str            # e.g., "0px 8px 24px rgba(0,0,0,0.12)"
    background_treatment: str   # e.g., "gradient #BDAEC9 to white, 45 degrees"
    texture: str                # e.g., "subtle grain", "clean and flat"
    mood_keywords: List[str]    # e.g., ["serene", "sophisticated", "inviting"]


@dataclass
class DesignFramework:
    """Complete design framework generated by Principal Designer AI"""
    # Identity
    framework_id: str           # Unique identifier
    framework_name: str         # e.g., "Serene Sophistication"
    design_philosophy: str      # 2-3 sentence design vision

    # Core Specs
    colors: List[ColorSpec]
    typography: TypographySpec
    layout: LayoutSpec
    visual_treatment: VisualTreatment

    # Story & Copy
    story_arc: StoryArc
    image_copy: List[ImageCopy]
    brand_voice: str            # e.g., "Warm, confident, aspirational"

    # Why This Works
    rationale: str              # Why this framework suits the product
    target_appeal: str          # Who this appeals to


class DesignFrameworkResponse(BaseModel):
    """API response model for design frameworks"""
    frameworks: List[Dict[str, Any]]
    product_analysis: str
    generation_notes: str


# ============================================================================
# THE PRINCIPAL DESIGNER PROMPT
# ============================================================================

PRINCIPAL_DESIGNER_PROMPT = '''You are a Principal Designer with 20+ years at top agencies (Apple, Nike, Pentagram).
You're known for creating cohesive, compelling Amazon listing image sets that convert browsers into buyers.

ANALYZE THIS PRODUCT:
Product Name: {product_name}
Brand Name: {brand_name}
Key Features: {features}
Target Audience: {target_audience}
Primary Color Preference: {primary_color}

YOUR TASK:
Generate 4 COMPLETELY UNIQUE design frameworks for this product's Amazon listing.
Each framework must be distinctly different in personality, color palette, and approach.
Think like you're presenting 4 options to a Fortune 500 client.

CRITICAL REQUIREMENTS FOR EACH FRAMEWORK:

1. COLOR PALETTE (3 colors ONLY with EXACT hex codes):
   - Primary (60%): The dominant color
   - Secondary (30%): Supporting color
   - Accent (10%): Pop of contrast
   Premium brands use FEWER colors, not more. Think Apple (white + silver + black).
   Include the color NAME (e.g., "Soft Lilac") and SPECIFIC usage instructions.
   Text colors derive from the palette — dark text uses Primary darkened, light text uses Secondary lightened.

2. TYPOGRAPHY (SPECIFIC font names that work well):
   Choose from real, commonly available fonts:
   - Headlines: Font name, weight, suggested size
   - Subheads: Font name, weight, suggested size
   - Body: Font name, weight, suggested size
   Good options: Montserrat, Playfair Display, Inter, Poppins, Oswald, Quicksand,
   Source Sans Pro, Roboto, Open Sans, Lato, Raleway, Nunito

3. STORY ARC (tailored to THIS product):
   - Theme: The overall narrative thread
   - Hook (Image 1): How the main image grabs attention
   - Reveal (Image 2): What story we're telling
   - Proof (Image 3): How we demonstrate value
   - Dream (Image 4): The aspirational lifestyle
   - Close (Image 5): The final convincing push

4. COPY FOR EACH IMAGE:
   - Image 1 (Main): Usually no text - describe the visual hook
   - Image 2 (Hero): Headline + optional subhead
   - Image 3 (Infographic 1): Headline + 3 feature callouts
   - Image 4 (Lifestyle): Aspirational headline
   - Image 5 (Comparison/Trust): Convincing headline + trust elements

5. LAYOUT SPECIFICATIONS:
   - Composition style
   - Whitespace philosophy
   - Product prominence approach
   - Text placement strategy
   - Visual flow pattern

6. VISUAL TREATMENT:
   - Lighting style and direction
   - Shadow specification (CSS-style)
   - Background treatment (gradients, colors, textures)
   - Overall texture approach
   - 5 mood keywords

7. RATIONALE:
   - Why this framework works for this product
   - Who it appeals to most

FRAMEWORK DIVERSITY REQUIREMENTS:
- Framework 1: Most likely to convert - safe but excellent
- Framework 2: Bold creative risk - unexpected but compelling
- Framework 3: Emotional connection focus - storytelling priority
- Framework 4: Premium/aspirational - elevate the product perception

OUTPUT FORMAT:
Return a valid JSON object with this exact structure:
{{
  "product_analysis": "Your 2-3 sentence analysis of the product and market positioning",
  "frameworks": [
    {{
      "framework_id": "framework_1",
      "framework_name": "Creative name for this approach",
      "design_philosophy": "2-3 sentence design vision",
      "colors": [
        {{"hex": "#XXXXXX", "name": "Color Name", "role": "primary", "usage": "60% - usage description"}},
        {{"hex": "#XXXXXX", "name": "Color Name", "role": "secondary", "usage": "30% - usage description"}},
        {{"hex": "#XXXXXX", "name": "Color Name", "role": "accent", "usage": "10% - usage description"}},
        {{"hex": "#XXXXXX", "name": "Color Name", "role": "text_dark", "usage": "Dark text on light backgrounds"}},
        {{"hex": "#XXXXXX", "name": "Color Name", "role": "text_light", "usage": "Light text on dark backgrounds"}}
      ],
      "typography": {{
        "headline_font": "Font Name",
        "headline_weight": "Bold",
        "headline_size": "48px",
        "subhead_font": "Font Name",
        "subhead_weight": "Regular",
        "subhead_size": "24px",
        "body_font": "Font Name",
        "body_weight": "Regular",
        "body_size": "16px",
        "letter_spacing": "0.5px"
      }},
      "story_arc": {{
        "theme": "The narrative thread",
        "hook": "Image 1 strategy",
        "reveal": "Image 2 story",
        "proof": "Image 3 demonstration",
        "dream": "Image 4 aspiration",
        "close": "Image 5 conviction"
      }},
      "image_copy": [
        {{"image_number": 1, "image_type": "main", "headline": "", "subhead": null, "feature_callouts": [], "cta": null}},
        {{"image_number": 2, "image_type": "infographic_1", "headline": "Headline text", "subhead": "Optional subhead", "feature_callouts": [], "cta": null}},
        {{"image_number": 3, "image_type": "infographic_2", "headline": "Headline text", "subhead": null, "feature_callouts": ["Feature 1", "Feature 2", "Feature 3"], "cta": null}},
        {{"image_number": 4, "image_type": "lifestyle", "headline": "Aspirational headline", "subhead": null, "feature_callouts": [], "cta": null}},
        {{"image_number": 5, "image_type": "comparison", "headline": "Trust headline", "subhead": null, "feature_callouts": [], "cta": "Call to action"}}
      ],
      "brand_voice": "Description of the copy tone and personality",
      "layout": {{
        "composition_style": "e.g., centered symmetric",
        "whitespace_philosophy": "e.g., generous breathing room",
        "product_prominence": "e.g., hero focus at 60% frame",
        "text_placement": "e.g., left-aligned blocks",
        "visual_flow": "e.g., Z-pattern reading flow"
      }},
      "visual_treatment": {{
        "lighting_style": "e.g., soft diffused from top-left",
        "shadow_spec": "e.g., 0px 8px 24px rgba(0,0,0,0.12)",
        "background_treatment": "e.g., gradient from #BDAEC9 to white, top to bottom",
        "texture": "e.g., subtle grain overlay",
        "mood_keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
      }},
      "rationale": "Why this framework works for this product",
      "target_appeal": "Who this most appeals to"
    }}
  ],
  "generation_notes": "Any notes about your creative decisions"
}}

Generate 4 frameworks following this exact structure. Be creative, be specific, be professional.
Every hex code must be valid. Every font must be real. Every headline must be compelling.
'''


# ============================================================================
# THE PRINCIPAL DESIGNER AI SERVICE
# ============================================================================

class DesignArchitectService:
    """
    Principal Designer AI that generates dynamic, professional design frameworks.

    This replaces static presets with AI-generated, product-specific frameworks.
    """

    def __init__(self, gemini_service):
        """
        Initialize with a Gemini service for AI generation.

        Args:
            gemini_service: Instance of GeminiService for text generation
        """
        self.gemini = gemini_service

    async def generate_frameworks(
        self,
        product_name: str,
        brand_name: Optional[str] = None,
        features: Optional[List[str]] = None,
        target_audience: Optional[str] = None,
        primary_color: Optional[str] = None,
        product_image_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Generate 4 unique design frameworks for a product.

        Args:
            product_name: The product title
            brand_name: Optional brand name
            features: List of key features
            target_audience: Target audience description
            primary_color: Optional preferred primary color (hex)
            product_image_path: Optional path to product image for analysis

        Returns:
            Dict with 'frameworks' list and metadata
        """
        # Build the prompt
        prompt = PRINCIPAL_DESIGNER_PROMPT.format(
            product_name=product_name,
            brand_name=brand_name or "Not specified",
            features=", ".join(features) if features else "Not specified",
            target_audience=target_audience or "General consumers",
            primary_color=primary_color or "AI to determine based on product",
        )

        logger.info(f"Generating design frameworks for: {product_name}")

        try:
            # Call Gemini for text generation
            response = await self.gemini.generate_text(
                prompt=prompt,
                max_tokens=8000,  # Need lots of tokens for 4 detailed frameworks
                temperature=0.8,  # Some creativity but structured
            )

            # Parse the JSON response
            frameworks_data = self._parse_response(response)

            logger.info(f"Generated {len(frameworks_data.get('frameworks', []))} frameworks")

            return frameworks_data

        except Exception as e:
            logger.error(f"Failed to generate frameworks: {e}")
            raise

    def _parse_response(self, response: str) -> Dict[str, Any]:
        """Parse the AI response into structured data"""
        # Try to extract JSON from the response
        try:
            # Find JSON in the response (it might have markdown code blocks)
            json_start = response.find('{')
            json_end = response.rfind('}') + 1

            if json_start == -1 or json_end == 0:
                raise ValueError("No JSON found in response")

            json_str = response[json_start:json_end]
            data = json.loads(json_str)

            # Validate structure
            if 'frameworks' not in data:
                raise ValueError("Response missing 'frameworks' key")

            if len(data['frameworks']) < 4:
                logger.warning(f"Only got {len(data['frameworks'])} frameworks, expected 4")

            return data

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse JSON: {e}")
            logger.debug(f"Raw response: {response[:500]}...")
            raise ValueError(f"Invalid JSON in AI response: {e}")

    def framework_to_prompt(self, framework: Dict[str, Any], image_type: str) -> str:
        """
        Convert a design framework to a complete prompt for image generation.

        Args:
            framework: The design framework dict
            image_type: Which image to generate (main, infographic_1, etc.)

        Returns:
            Complete prompt string for Gemini image generation
        """
        # Find the copy for this image
        image_copy = None
        image_number = {
            'main': 1,
            'infographic_1': 2,
            'infographic_2': 3,
            'lifestyle': 4,
            'comparison': 5,
        }.get(image_type, 1)

        for copy in framework.get('image_copy', []):
            if copy.get('image_number') == image_number:
                image_copy = copy
                break

        # Build color section
        colors = framework.get('colors', [])
        color_section = "[COLOR PALETTE - EXACT VALUES]\n"
        for color in colors:
            color_section += f"- {color['role'].upper()}: {color['hex']} ({color['name']}) - {color['usage']}\n"

        # Build typography section
        typo = framework.get('typography', {})
        typo_section = f"""[TYPOGRAPHY - EXACT SPECIFICATIONS]
Headlines: {typo.get('headline_font', 'Montserrat')} {typo.get('headline_weight', 'Bold')}, {typo.get('headline_size', '48px')}
Subheads: {typo.get('subhead_font', 'Montserrat')} {typo.get('subhead_weight', 'Regular')}, {typo.get('subhead_size', '24px')}
Body: {typo.get('body_font', 'Inter')} {typo.get('body_weight', 'Regular')}, {typo.get('body_size', '16px')}
Letter Spacing: {typo.get('letter_spacing', '0px')}
"""

        # Build story arc section
        story = framework.get('story_arc', {})
        story_section = f"""[STORY ARC - THIS IS IMAGE {image_number} OF 5]
Theme: {story.get('theme', '')}
This Image's Role: {story.get(['hook', 'reveal', 'proof', 'dream', 'close'][image_number - 1], '')}
"""

        # Build copy section
        copy_section = "[COPY FOR THIS IMAGE]\n"
        if image_copy:
            if image_copy.get('headline'):
                copy_section += f"HEADLINE: \"{image_copy['headline']}\"\n"
            if image_copy.get('subhead'):
                copy_section += f"SUBHEAD: \"{image_copy['subhead']}\"\n"
            if image_copy.get('feature_callouts'):
                copy_section += "FEATURE CALLOUTS:\n"
                for i, callout in enumerate(image_copy['feature_callouts'], 1):
                    copy_section += f"  {i}. {callout}\n"
            if image_copy.get('cta'):
                copy_section += f"CTA: \"{image_copy['cta']}\"\n"
        else:
            if image_type == 'main':
                copy_section += "No text - pure product hero shot on white background\n"

        # Build layout section
        layout = framework.get('layout', {})
        layout_section = f"""[LAYOUT SPECIFICATIONS]
Composition: {layout.get('composition_style', 'centered')}
Whitespace: {layout.get('whitespace_philosophy', 'balanced')}
Product Prominence: {layout.get('product_prominence', 'hero focus')}
Text Placement: {layout.get('text_placement', 'as appropriate')}
Visual Flow: {layout.get('visual_flow', 'natural reading order')}
"""

        # Build visual treatment section
        visual = framework.get('visual_treatment', {})
        visual_section = f"""[VISUAL TREATMENT]
Lighting: {visual.get('lighting_style', 'soft studio lighting')}
Shadows: {visual.get('shadow_spec', 'subtle drop shadows')}
Background: {visual.get('background_treatment', 'clean and appropriate')}
Texture: {visual.get('texture', 'clean')}
Mood: {', '.join(visual.get('mood_keywords', ['professional', 'appealing']))}
"""

        # Build the complete prompt
        prompt = f"""[CREATIVE BRIEF: {framework.get('framework_name', 'Design Framework')}]
{framework.get('design_philosophy', '')}

Brand Voice: {framework.get('brand_voice', 'Professional and appealing')}

{color_section}

{typo_section}

{story_section}

{copy_section}

{layout_section}

{visual_section}

[AMAZON REQUIREMENTS]
- Image {image_number} of 5 in listing set
- {'Pure white background (#FFFFFF) required' if image_type == 'main' else 'Background per design brief'}
- 1500x1500px minimum, 1:1 aspect ratio
- Must be cohesive with other images in set
- Thumbnail must be clear at 100px

[COHESION REQUIREMENT]
All 5 images in this set MUST share:
- The exact color palette above
- The typography specifications above
- The visual treatment above
- The brand voice above
The customer should instantly recognize these images belong together.
"""

        return prompt


def get_design_architect_service(gemini_service) -> DesignArchitectService:
    """Factory function to create DesignArchitectService"""
    return DesignArchitectService(gemini_service)
