"""
Pydantic Schemas for Image Generation API
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict
from enum import Enum


class ImageTypeEnum(str, Enum):
    """Available image types for generation"""
    MAIN = "main"
    INFOGRAPHIC_1 = "infographic_1"
    INFOGRAPHIC_2 = "infographic_2"
    LIFESTYLE = "lifestyle"
    COMPARISON = "comparison"
    STYLE_PREVIEW = "style_preview"
    APLUS_0 = "aplus_0"
    APLUS_1 = "aplus_1"
    APLUS_2 = "aplus_2"
    APLUS_3 = "aplus_3"
    APLUS_4 = "aplus_4"
    APLUS_5 = "aplus_5"


class GenerationStatusEnum(str, Enum):
    """Generation status values"""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETE = "complete"
    PARTIAL = "partial"
    FAILED = "failed"


class KeywordInput(BaseModel):
    """Keyword with optional intent classification"""
    keyword: str = Field(..., min_length=1, max_length=100)
    intents: List[str] = Field(default_factory=list)


class StylePreview(BaseModel):
    """Style preset info for selection"""
    id: str
    name: str
    description: str
    color_palette: List[str]
    mood: str


class BrandVibeEnum(str, Enum):
    """Brand personality vibes for MASTER level creative briefs"""
    PREMIUM_LUXURY = "premium_luxury"      # Elegant, exclusive, aspirational
    CLEAN_MODERN = "clean_modern"          # Minimal, tech, sophisticated
    BOLD_ENERGETIC = "bold_energetic"      # Dynamic, confident, action
    NATURAL_ORGANIC = "natural_organic"    # Earthy, authentic, wholesome
    PLAYFUL_FUN = "playful_fun"            # Vibrant, youthful, joyful
    CLINICAL_TRUST = "clinical_trust"      # Professional, scientific, reliable


# ============================================================================
# MASTER LEVEL: Design Framework Types
# ============================================================================

class ColorSpec(BaseModel):
    """Exact color specification from Principal Designer AI"""
    hex: str
    name: str
    role: str  # primary, secondary, accent, text_dark, text_light
    usage: str


class TypographySpec(BaseModel):
    """Typography specifications with exact font names and sizes"""
    headline_font: str
    headline_weight: str
    headline_size: str
    subhead_font: str
    subhead_weight: str
    subhead_size: str
    body_font: str
    body_weight: str
    body_size: str
    letter_spacing: str


class StoryArc(BaseModel):
    """Story arc across 5 images"""
    theme: str
    hook: str
    reveal: str
    proof: str
    dream: str
    close: str


class ImageCopy(BaseModel):
    """Copy strategy for each image type"""
    image_number: int
    image_type: str
    headline: str
    subhead: Optional[str] = None
    feature_callouts: List[str] = Field(default_factory=list)
    cta: Optional[str] = None


class ImageGenerationPrompt(BaseModel):
    """
    Detailed generation prompt for each image type.

    GPT-4o Vision Principal Designer AI generates these PRODUCT-SPECIFIC prompts
    that are then used directly with Gemini for image generation.
    Each prompt is highly detailed and specific to:
    - The actual product being photographed
    - The specific image type (main, infographic, lifestyle, etc.)
    - The design framework style
    """
    image_number: int  # 1-5
    image_type: str    # main, infographic_1, infographic_2, lifestyle, comparison
    prompt: str        # The full, detailed generation prompt (can be 500+ words)
    composition_notes: str  # Brief notes on what this image should show
    key_elements: List[str] = Field(default_factory=list)  # Must-have elements in the image


class LayoutSpec(BaseModel):
    """Layout specifications"""
    composition_style: str
    whitespace_philosophy: str
    product_prominence: str
    text_placement: str
    visual_flow: str


class VisualTreatment(BaseModel):
    """Visual treatment specifications"""
    lighting_style: str
    shadow_spec: str
    background_treatment: str
    texture: str
    mood_keywords: List[str] = Field(default_factory=list)


class DesignFramework(BaseModel):
    """Complete design framework from Principal Designer AI"""
    framework_id: str
    framework_name: str
    framework_type: Optional[str] = None
    design_philosophy: str
    colors: List[ColorSpec]
    typography: TypographySpec
    story_arc: StoryArc
    image_copy: List[ImageCopy]
    brand_voice: str
    layout: LayoutSpec
    visual_treatment: VisualTreatment
    rationale: str
    target_appeal: str

    # CRITICAL: Detailed generation prompts for each of the 5 image types
    # These are product-specific prompts generated by GPT-4o Vision that tell
    # the image generator EXACTLY what to create - with full detail
    generation_prompts: List[ImageGenerationPrompt] = Field(
        default_factory=list,
        description="Detailed generation prompts for each of the 5 image types. "
                    "Each prompt is 300-600 words and specific to the product."
    )


class GenerationRequest(BaseModel):
    """Request to generate listing images"""
    product_title: str = Field(..., min_length=1, max_length=200)
    feature_1: Optional[str] = Field(None, max_length=100)  # Now optional
    feature_2: Optional[str] = Field(None, max_length=100)  # Now optional
    feature_3: Optional[str] = Field(None, max_length=100)  # Now optional
    target_audience: Optional[str] = Field(None, max_length=150)  # Now optional
    keywords: List[KeywordInput] = Field(default_factory=list, max_length=20)
    upload_path: str = Field(..., description="Path to uploaded primary product image")
    additional_upload_paths: List[str] = Field(
        default_factory=list,
        max_length=4,
        description="Additional product images (up to 4) for better AI context"
    )

    # Brand & Style
    brand_name: Optional[str] = Field(None, max_length=100)
    brand_colors: List[str] = Field(default_factory=list, max_length=5)
    logo_path: Optional[str] = Field(None, description="Path to uploaded brand logo image")
    style_id: Optional[str] = Field(None, description="Selected style preset ID (legacy)")

    # MASTER Level: Brand Vibe - drives the entire creative brief
    brand_vibe: Optional[BrandVibeEnum] = Field(
        None,
        description="Brand personality vibe for MASTER level creative brief generation"
    )
    primary_color: Optional[str] = Field(
        None,
        pattern=r"^#[0-9A-Fa-f]{6}$",
        description="Primary brand color in hex format (e.g., #2196F3)"
    )

    # Style Reference Image - applies consistent style across all images
    style_reference_path: Optional[str] = Field(
        None,
        description="Path to style reference image - AI will match this visual style"
    )

    # Color Palette Options - if not specified, AI generates cohesive palette
    color_count: Optional[int] = Field(
        None,
        ge=2,
        le=6,
        description="Number of colors in palette (2-6). If not specified, AI decides."
    )
    color_palette: List[str] = Field(
        default_factory=list,
        max_length=6,
        description="Specific hex colors for palette. If empty, AI generates colors."
    )

    # MASTER LEVEL: Complete design framework from Principal Designer AI
    design_framework: Optional[DesignFramework] = Field(
        None,
        description="Complete design framework from GPT-4o Vision Principal Designer AI"
    )

    # Global note/instructions that will be applied to ALL generated images
    global_note: Optional[str] = Field(
        None,
        max_length=2000,
        description="Global instructions applied to all image generations (e.g., style preferences, things to avoid)"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "product_title": "Organic Vitamin D3 Gummies - Natural Immune Support",
                "feature_1": "5000 IU Vitamin D3 per serving",
                "feature_2": "Organic, non-GMO ingredients",
                "feature_3": "Great-tasting natural berry flavor",
                "target_audience": "Health-conscious adults 30-55",
                "keywords": [
                    {"keyword": "vitamin d gummies", "intents": ["durability", "style"]},
                    {"keyword": "immune support", "intents": ["problem_solution"]}
                ],
                "upload_path": "storage/uploads/abc123/product.png",
                "brand_name": "VitaGlow",
                "brand_colors": ["#4CAF50", "#FFC107"],
                "logo_path": "storage/uploads/abc123/logo.png",
                "brand_vibe": "natural_organic",
                "primary_color": "#2D5016",
                "style_reference_path": "storage/uploads/abc123/style_ref.png",
                "color_count": 4,
                "color_palette": ["#2D5016", "#F5F1E8", "#8B7355", "#A8C686"]
            }
        }
    )


class StylePreviewRequest(BaseModel):
    """Request to generate style preview images"""
    product_title: str = Field(..., min_length=1, max_length=200)
    feature_1: Optional[str] = Field(None, max_length=100)
    upload_path: str = Field(..., description="Path to uploaded product image")
    logo_path: Optional[str] = Field(None, description="Path to uploaded brand logo image")
    brand_colors: List[str] = Field(default_factory=list)
    style_ids: List[str] = Field(
        default_factory=lambda: ["clean_minimal", "bold_vibrant", "luxury_premium", "natural_organic"],
        description="Style IDs to preview"
    )

    # Style Reference Image - for consistent style across previews
    style_reference_path: Optional[str] = Field(
        None,
        description="Path to style reference image - AI will match this visual style"
    )

    # Color Palette Options
    color_count: Optional[int] = Field(None, ge=2, le=6)
    color_palette: List[str] = Field(default_factory=list, max_length=6)


class StylePreviewResult(BaseModel):
    """Result for a single style preview"""
    style_id: str
    style_name: str
    status: GenerationStatusEnum
    image_url: Optional[str] = None
    error_message: Optional[str] = None


class StylePreviewResponse(BaseModel):
    """Response from style preview generation"""
    session_id: str
    previews: List[StylePreviewResult]


class ImageResult(BaseModel):
    """Result for a single generated image"""
    image_type: ImageTypeEnum
    status: GenerationStatusEnum
    storage_path: Optional[str] = None
    error_message: Optional[str] = None


class GenerationResponse(BaseModel):
    """Response from image generation request"""
    session_id: str
    status: GenerationStatusEnum
    images: List[ImageResult]


class SessionStatusResponse(BaseModel):
    """Status check response for a generation session"""
    session_id: str
    status: GenerationStatusEnum
    product_title: str
    style_id: Optional[str] = None
    created_at: str
    completed_at: Optional[str] = None
    images: List[ImageResult]


class SingleImageRequest(BaseModel):
    """Request to generate a single image type"""
    session_id: str
    image_type: ImageTypeEnum
    note: Optional[str] = Field(
        None,
        max_length=2000,
        description="Optional note/instructions for this specific image regeneration"
    )


class SingleImageResponse(BaseModel):
    """Response for single image generation"""
    session_id: str
    image_type: ImageTypeEnum
    status: GenerationStatusEnum
    storage_path: Optional[str] = None
    error_message: Optional[str] = None


class SelectStyleRequest(BaseModel):
    """Request to select a style for final generation"""
    session_id: str
    style_id: str
